theme: jekyll-theme-time-machine
title: Welcome To Essential Linear-Algebra For Data Science
description: Learn or Refresh your Linear Algebra skills with intuitive visualizations and hands-on exercises
